# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-$(CONFIG_VIDEO_SUNXI) += sunxi_display.o sunxi_lcd.o
obj-$(CONFIG_VIDEO_DE2) += sunxi_de2.o
obj-$(CONFIG_VIDEO_DW_HDMI) += sunxi_dw_hdmi.o
obj-$(CONFIG_VIDEO_SUNXI_T113) += sunxi_de2.o sun6i_mipi_dsi.o sun6i_mipi_dphy.o sun8i_tcon_top.o
obj-$(CONFIG_VIDEO_DT_SIMPLEFB) += simplefb_common.o

