# SPDX-License-Identifier: GPL-2.0+
#
# (C) Copyright 2000-2007
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.

obj-$(CONFIG_VIDEO_SUNXI) += sunxi_display.o simplefb_common.o lcdc.o tve_common.o ../videomodes.o
obj-$(CONFIG_VIDEO_DE2) += sunxi_de2.o simplefb_common.o lcdc.o sunxi_lcd.o sun8i_tcon_top.o
obj-$(CONFIG_VIDEO_DW_HDMI) += sunxi_dw_hdmi.o
obj-$(CONFIG_VIDEO_LCD_DSI_TX) += sun6i_mipi_dsi.o
